---
# This meta data should be filled out.
title: Deck title
description: Deck description
keywords: [deck.js, talk]
locale: en_US
site_name: Site name
color: "#3f51b5"

# This meta data is optional.
# determiner: null
# image: https://io.evansosenko.com/jekyll-and-deck.js/preview.png
# audio: https://io.evansosenko.com/jekyll-and-deck.js/talk.mp3
# video: https://io.evansosenko.com/jekyll-and-deck.js/talk.mpg
# type: website
#
twitter:
  card: summary
  site: "@evansosenko"
  creator: "@evansosenko"
